name: Build check

on:
    workflow_dispatch:
    push:
        branches:
            - production

env:
    VITE_PUBLIC_API_URL: https://api.arrhes.com
    VITE_PUBLIC_PLATFORM_URL: https://espace.arrhes.com
    VITE_PUBLIC_WEBSITE_URL: https://arrhes.com

jobs:
    build:
        runs-on: ubuntu-22.04

        permissions:
            contents: read
            packages: read

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Create .env file
                run: |
                    echo VITE_PUBLIC_API_URL=${{ env.VITE_PUBLIC_API_URL }} >> .env
                    echo VITE_PUBLIC_PLATFORM_URL=${{ env.VITE_PUBLIC_PLATFORM_URL }} >> .env
                    echo VITE_PUBLIC_WEBSITE_URL=${{ env.VITE_PUBLIC_WEBSITE_URL }} >> .env

            -   name: Install pnpm
                uses: pnpm/action-setup@v4
                with:
                    version: 9
                    run_install: false

            -   name: Install Node.js
                uses: actions/setup-node@v4
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    node-version: 20
                    registry-url: https://npm.pkg.github.com
                    scope: arrhes
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   name: Install dependencies
                run: pnpm install

            -   name: Build
                run: pnpm run build
