name: Deploy to server

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
        -   name: Checkout repository
            uses: actions/checkout@v4

        -   name: Deploy the new image
            uses: appleboy/ssh-action@v1.1.0
            with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                password: ${{ secrets.SSH_PASSWORD }}
                script: |
                    docker container remove platform --force
                    docker compose -f ~/arrhes/platform/compose.yaml pull
                    docker compose -f ~/arrhes/platform/compose.yaml up -d
