name: Publish the package

on:
    workflow_dispatch:
    release:
        types: [published]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    VITE_PUBLIC_API_URL: https://api.arrhes.com
    VITE_PUBLIC_PLATFORM_URL: https://espace.arrhes.com
    VITE_PUBLIC_WEBSITE_URL: https://arrhes.com
    
jobs:
    publish:

        runs-on: ubuntu-22.04

        permissions:
            contents: read
            packages: write

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Login to the container registry
                uses: docker/login-action@v3
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Extract metadata
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: ./.docker/Dockerfile
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    build-args: |
                        VITE_PUBLIC_API_URL=${{ env.VITE_PUBLIC_API_URL }}
                        VITE_PUBLIC_PLATFORM_URL=${{ env.VITE_PUBLIC_PLATFORM_URL }}
                        VITE_PUBLIC_WEBSITE_URL=${{ env.VITE_PUBLIC_WEBSITE_URL }}
                    secrets: |
                        "github_token=${{ secrets.GITHUB_TOKEN }}"
