name: Build check

on:
    push:
        branches:
            - production

jobs: 
    build:

        runs-on: ubuntu-22.04

        permissions:
            contents: read

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            
            -   name: Install pnpm
                uses: pnpm/action-setup@v4
                with:
                    version: 9
                    run_install: false
        
            -   name: Install Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 20
                    registry-url: https://npm.pkg.github.com
            
            -   name: Install dependencies
                run: pnpm install

            -   name: Build
                run: pnpm run build
