# ==============================================================================
# Tunnel Override - Exposes API via Cloudflare Quick Tunnel
# ==============================================================================
# Adds a cloudflared service that creates a public tunnel to the API.
# Used for Mollie webhook testing in local development.
#
# Usage (via justfile):
#   just dev tunnel
#
# Flow:
#   1. The justfile starts ONLY the tunnel service first
#   2. Waits for cloudflared to print the *.trycloudflare.com URL
#   3. Starts all remaining services with API_BASE_URL set to the tunnel URL
#
# The tunnel container does NOT depend on the API — cloudflared establishes
# the tunnel immediately and retries backend connections as needed.
# ==============================================================================

services:
  tunnel:
    container_name: arrhes-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --url http://api:3000 --no-autoupdate

  # When API_BASE_URL is set on the host (by the justfile after reading the
  # tunnel URL), it is injected into the container and overrides the .env value.
  # When it is NOT set on the host, this directive has no effect.
  api:
    environment:
      - API_BASE_URL
